# Generated by Django 3.1.2 on 2020-10-21 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookz', '0003_auto_20201021_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='Url'),
        ),
    ]
